"""Adiciona tabela inscricoes

Revision ID: 188a6c6ca723
Revises: c9f36532dae5
Create Date: 2026-07-20 11:33:40.395336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188a6c6ca723'
down_revision = 'c9f36532dae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inscricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidata_id', sa.Integer(), nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=False),
    sa.Column('clube_slug', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nome_associada', sa.String(length=120), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('cpf_associada', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=False),
    sa.Column('tipo_ensino', sa.String(length=20), nullable=False),
    sa.Column('nome_escola', sa.String(length=200), nullable=True),
    sa.Column('nome_mae', sa.String(length=120), nullable=False),
    sa.Column('data_nascimento_mae', sa.Date(), nullable=False),
    sa.Column('profissao_mae', sa.String(length=120), nullable=False),
    sa.Column('celular_mae', sa.String(length=32), nullable=False),
    sa.Column('email_mae', sa.String(length=120), nullable=False),
    sa.Column('nome_pai', sa.String(length=120), nullable=False),
    sa.Column('data_nascimento_pai', sa.Date(), nullable=False),
    sa.Column('profissao_pai', sa.String(length=120), nullable=False),
    sa.Column('celular_pai', sa.String(length=32), nullable=False),
    sa.Column('email_pai', sa.String(length=120), nullable=False),
    sa.Column('responsavel_financeiro', sa.String(length=20), nullable=False),
    sa.Column('cpf_responsavel_financeiro', sa.Text(), nullable=False),
    sa.Column('como_conheceu', sa.Text(), nullable=False),
    sa.Column('esportes_hobbies', sa.Text(), nullable=False),
    sa.Column('situacao_pais', sa.Text(), nullable=False),
    sa.Column('irmaos', sa.Text(), nullable=False),
    sa.Column('caracteristicas', sa.Text(), nullable=False),
    sa.Column('pontos_a_trabalhar', sa.Text(), nullable=False),
    sa.Column('alergias', sa.Text(), nullable=False),
    sa.Column('medicamento_administrado', sa.Text(), nullable=False),
    sa.Column('interesse_doutrina', sa.Boolean(), nullable=False),
    sa.Column('ciente_regimento', sa.Boolean(), nullable=False),
    sa.Column('autoriza_imagem', sa.Boolean(), nullable=False),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidata_id'], ['candidatas.id'], ),
    sa.ForeignKeyConstraint(['familia_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inscricoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inscricoes_candidata_id'), ['candidata_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_inscricoes_clube_slug'), ['clube_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_inscricoes_familia_id'), ['familia_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inscricoes_familia_id'))
        batch_op.drop_index(batch_op.f('ix_inscricoes_clube_slug'))
        batch_op.drop_index(batch_op.f('ix_inscricoes_candidata_id'))

    op.drop_table('inscricoes')
    # ### end Alembic commands ###
