"""Adiciona campos de familia no Usuario

Revision ID: c4abc399bec6
Revises: d6ed5e2b12c6
Create Date: 2026-07-06 10:03:37.246709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4abc399bec6'
down_revision = 'd6ed5e2b12c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nome_candidata', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('idade_candidata', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('idade_candidata')
        batch_op.drop_column('nome_candidata')
        batch_op.drop_column('endereco')
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
