"""Remove nome_candidata e idade_candidata do Usuario

Revision ID: c9f36532dae5
Revises: c4abc399bec6
Create Date: 2026-07-07 14:53:45.933586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f36532dae5'
down_revision = 'c4abc399bec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('idade_candidata')
        batch_op.drop_column('nome_candidata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_candidata', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('idade_candidata', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
