"""Sprint M: adiciona clube_slug e role atualizada no Usuario

Revision ID: d6ed5e2b12c6
Revises: 
Create Date: 2026-06-18 17:02:07.327931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ed5e2b12c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.alter_column('autor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clube_slug', sa.String(length=64), nullable=True))
        batch_op.alter_column('senha_hash',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_usuarios_clube_slug'), ['clube_slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_clube_slug'))
        batch_op.alter_column('role',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('senha_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('clube_slug')

    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.alter_column('autor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
